// Generated by CoffeeScript 1.3.3
(function() {

  jQuery(function() {
    var Tweets;
    $('a').live('click', function() {
      return $(this).attr('target', '_blank');
    });
    Tweets = {
      search_attributes: {
        q: '@tomayorford OR "Rob Ford" OR "Mayor Ford" OR #robford -RT',
        rpp: 42,
        result_type: 'recent'
      },
      fetch: function() {
        return $.ajax({
          url: 'http://search.twitter.com/search.json',
          data: this.search_attributes,
          dataType: 'jsonp',
          success: this.render
        });
      },
      render: function(json) {
        $('.tweets').hide();
        $.each(json.results, function(_, tweet) {
          var datetime, el;
          el = $('.templates .twitter-tweet').first().clone();
          datetime = new Date(tweet.created_at);
          $('p', el).html(tweet.text);
          $('a', el).attr('href', 'https://twitter.com/twitterapi/status/' + tweet.id_str).attr('data-datetime', datetime.toISOString()).text(tweet.created_at);
          return $('.tweets').append(el);
        });
        return $.getScript('//platform.twitter.com/widgets.js', function() {
          return $('.tweets').fadeTo('slow', 0.9);
        });
      }
    };
    Tweets.fetch();
    return $('.about .keywords').text(Tweets.search_attributes.q);
  });

}).call(this);
