// Generated by CoffeeScript 1.3.3
(function() {

  angular.module('RobFord', []);

  window.RobFordController = function($scope) {
    $scope.search = function() {
      var url;
      $('.tweets').fadeTo(0, 0.0);
      url = "https://search.twitter.com/search.json?q=" + (escape($scope.search_terms)) + "&callback=?";
      return $.getJSON(url, function(response) {
        $scope.$apply(function() {
          return $scope.tweets = response.results;
        });
        return $.getScript('//platform.twitter.com/widgets.js', function() {
          return $('.tweets').delay(300).fadeTo('fast', 0.9);
        });
      });
    };
    $scope.search_terms = '@tomayorford OR "Rob Ford" OR "Mayor Ford" OR #robford -RT';
    return $scope.search();
  };

  jQuery(function() {
    return $('a').live('click', function() {
      return $(this).attr('target', '_blank');
    });
  });

}).call(this);
