source :rubygems

gem 'serve', '1.5.1'

# Use edge instead:
# gem 'serve', :git => 'git://github.com/jlong/serve.git'

gem 'sass'

# Markdown and Textile
# gem 'rdiscount' # Markdown
# gem 'RedCloth'  # Textile

# Other templating languages
# gem 'erubis'
gem 'haml'
# gem 'slim'
# gem 'radius'
# gem 'less'

# Coffee Script
gem 'rack-coffee'

# Use Thin for the Web server
gem 'thin'
